Give some more control over build process
- Generate a version number even for git repos that have no tags,
- Allow (somewhat hacky) use of tarball source,
- Allow manual specification of archive type (mostly for use with tarball source),
- Allow manual specification of COPYRIGHT.

diff --git a/bin/mksrcarc b/bin/mksrcarc
--- a/bin/mksrcarc
+++ b/bin/mksrcarc
@@ -4,11 +4,10 @@ source "$(dirname "$0")"/../lib/init
 {
 (($#==3)) || { echo "Usage: $(basename $0) <url> <revision> <suffix>" && exit 2 ;}
 url=$1
-SRCREV=$2
+rev=$2
 suffix=${3:-tar.gz}
 case "$url" in
 *.git)
-  rev=${SRCREV:-HEAD}
   dir=$(basename "$url")
   if [[ -d "$dir" ]]; then
     git --git-dir="$dir" fetch origin +master:master
@@ -16,11 +15,19 @@ case "$url" in
     git clone --bare "$url" "$dir"
   fi
   SRCNAME=$(basename "$dir" .git)
-  SRCVER=$(git --git-dir="$dir" describe --match 'v*' "$rev" | sed 's/^v//')
+  SRCREV=$(git --git-dir="$dir" describe --always "$rev") || { echo "Cannot find revision $rev" && exit 1;}
+  SRCVER=$(git --git-dir="$dir" describe --match 'v*' "$rev" 2>/dev/null | sed 's/^v//')
+  SRCVER=${SRCVER:-0-$(git --git-dir="$dir" rev-list "$rev" | wc -l)-g$SRCREV}
   namever=$SRCNAME-$SRCVER
   SRCARC=$namever.$suffix
   git --git-dir="$dir" archive --prefix="$namever/" -o "$SRCARC" "$rev"
-  SRCREV=${SRCREV:-$(git --git-dir="$dir" describe --always "$rev")}
+  ;;
+http://*)
+  wget -N "$url"
+  SRCARC=$(basename "$url")
+  SRCNAME=$(basename "$url" "$suffix")
+  SRCREV=$2
+  SRCVER=$2
   ;;
 *)
   echo "Unknown repository type"
